services:

  mongo-express:
    image: mongo-express:0.54
    # depends_on:
    #   - mongo
    restart: on-failure
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: app
      ME_CONFIG_MONGODB_ADMINPASSWORD: app
      ME_CONFIG_MONGODB_URL: mongodb://app:app@mongo:27017/
      ME_CONFIG_SITE_BASEURL: "/mongo-express/"

  # nginx:
  #   depends_on:
  #     - mongo_express
